### ISSUE TITLE
How do I train detector part only for any dataset?

### ISSUE THREAD

**Issue by Agrawalchitranshu** [ahmetgunduz/Real-time-GesRec#51] opened 2020-04-06 11:02 UTC
There is no detector checkpoint is added to the run_offline.py file while calling main.py.
Is there any other way to do so?

**Comment by ahmetgunduz** [comment] 2020-04-06 12:30
Detector is just a binary classification model. So if you choose `n_classes` =  1 and right annotation files, then you can train a detector using `run_offline.py`

**Comment by Agrawalchitranshu** [comment] 2020-04-06 12:47
Thanks, but I have one more doubt, like how does detector work, does it take each frame from the frames one by one and detects whether it is 1 or 0 and does this process work for all the frames?

**Comment by ahmetgunduz** [comment] 2020-04-07 12:34
It has a `sample_duration` parameter which stands for the number of consecutive frames to fed into the model. In real time "online" scenario, I slided a windows size of 8, meaning `sample_duration=8`, by one frame. You are free to use different setting. You can get frames one by one as I did, but you can use the same detector for larger sliding factor.

**Comment by Agrawalchitranshu** [comment] 2020-04-08 14:27
Thanks a lot for the help.

**Comment by ahmetgunduz** [comment] 2020-04-09 19:59
You are welcome, hope that it helps. I am assuming the issue is solved, so I am closing it.

**Closed by ahmetgunduz** 2020-04-09 19:59 UTC
